[project]
name = "advisor"
version = "0.1.0"
description = "advisor using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.130.0,<1.0.0"
]

[project.scripts]
advisor = "advisor.main:run"
run_crew = "advisor.main:run"
train = "advisor.main:train"
replay = "advisor.main:replay"
test = "advisor.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"

[tool.uv]
required-environments = [
    "sys_platform == 'darwin' and platform_machine == 'x86_64'"
]
[tool.uv.overrides]
onnxruntime = "==1.19.2"
[dependencies]
chromadb = ">=1.1.1"